"""create catalog and inventory tables

Revision ID: 17b16203d117
Revises: e2c96fc9abb3
Create Date: 2026-09-14 11:05:47.357816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '17b16203d117'
down_revision: Union[str, Sequence[str], None] = 'e2c96fc9abb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_order_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_price IS NULL OR discount_price >= 0', name='chk_product_discount_price'),
    sa.CheckConstraint('min_order_qty > 0', name='chk_product_min_qty'),
    sa.CheckConstraint('price >= 0', name='chk_product_price'),
    sa.CheckConstraint('unit_value > 0', name='chk_product_unit_value'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reserved_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_quantity >= 0', name='chk_inventory_available'),
    sa.CheckConstraint('reorder_level >= 0', name='chk_inventory_reorder'),
    sa.CheckConstraint('reserved_quantity <= available_quantity', name='chk_inventory_reserved_not_excess'),
    sa.CheckConstraint('reserved_quantity >= 0', name='chk_inventory_reserved'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            transaction_type IN (\n                'STOCK_IN',\n                'ORDER_RESERVED',\n                'ORDER_SOLD',\n                'ORDER_CANCELLED',\n                'MANUAL_ADJUSTMENT',\n                'DAMAGED',\n                'RETURNED'\n            )\n            ", name='chk_inventory_transaction_type'),
    sa.CheckConstraint('quantity > 0', name='chk_inventory_transaction_quantity'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    
    
    
    
#     op.create_index(
#     "uq_user_default_address",
#     "user_addresses",
#     ["user_id"],
#     unique=True,
#     postgresql_where=sa.text(
#         "is_default = true"
#     ),
# )

#     op.create_index(
#         "uq_user_active_cart",
#         "carts",
#         ["user_id"],
#         unique=True,
#         postgresql_where=sa.text(
#             "status = 'ACTIVE'"
#         ),
#     )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    
#     op.drop_index(
#     "uq_user_active_cart",
#     table_name="carts",
# )

#     op.drop_index(
#         "uq_user_default_address",
#         table_name="user_addresses",
#     )
    # ### end Alembic commands ###