"""add phone otp sessions

Revision ID: 21b4e1fc96bd
Revises: 06f8a33e4195
Create Date: 2026-09-23 15:41:03.313901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '21b4e1fc96bd'
down_revision: Union[str, Sequence[str], None] = '06f8a33e4195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otp_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resend_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otp_sessions_phone'), 'phone_otp_sessions', ['phone'], unique=False)
    op.create_index(op.f('ix_phone_otp_sessions_provider_request_id'), 'phone_otp_sessions', ['provider_request_id'], unique=True)
    op.create_index(op.f('ix_phone_otp_sessions_purpose'), 'phone_otp_sessions', ['purpose'], unique=False)
    op.create_index(op.f('ix_phone_otp_sessions_user_id'), 'phone_otp_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_otp_sessions_user_id'), table_name='phone_otp_sessions')
    op.drop_index(op.f('ix_phone_otp_sessions_purpose'), table_name='phone_otp_sessions')
    op.drop_index(op.f('ix_phone_otp_sessions_provider_request_id'), table_name='phone_otp_sessions')
    op.drop_index(op.f('ix_phone_otp_sessions_phone'), table_name='phone_otp_sessions')
    op.drop_table('phone_otp_sessions')
    # ### end Alembic commands ###