"""add delivery otp and cod fields

Revision ID: 46d6f79124f3
Revises: 6091ef8231c7
Create Date: 2026-10-05 16:37:39.619161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '46d6f79124f3'
down_revision: Union[str, Sequence[str], None] = '6091ef8231c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###