"""add commerce settings

Revision ID: 49486411c95e
Revises: f4381d7048a9
Create Date: 2026-09-24 11:34:04.600318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '49486411c95e'
down_revision: Union[str, Sequence[str], None] = 'f4381d7048a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commerce_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minimum_order_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), server_default='16.00', nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delivery_fee >= 0', name='chk_commerce_settings_delivery_fee_non_negative'),
    sa.CheckConstraint('id = 1', name='chk_commerce_settings_singleton'),
    sa.CheckConstraint('minimum_order_amount >= 0', name='chk_commerce_settings_minimum_non_negative'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    
    
    commerce_settings_table = sa.table(
    "commerce_settings",

    sa.column(
        "id",
        sa.Integer(),
    ),

    sa.column(
        "minimum_order_amount",
        sa.Numeric(10, 2),
    ),

    sa.column(
        "delivery_fee",
        sa.Numeric(10, 2),
    ),

    sa.column(
        "updated_by",
        sa.Integer(),
    ),
)


    op.bulk_insert(
        commerce_settings_table,
        [
            {
                "id": 1,
                "minimum_order_amount": 0.00,
                "delivery_fee": 16.00,
                "updated_by": None,
            }
        ],
    )
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commerce_settings')
    # ### end Alembic commands ###