"""duplicate delivery partner migration - no operation

Revision ID: 6091ef8231c7
Revises: bde848467272
"""

from typing import Sequence, Union


revision: str = "6091ef8231c7"

down_revision: Union[
    str,
    Sequence[str],
    None,
] = "bde848467272"

branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None

depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    """
    No operation.

    Delivery partner tables and base assignment schema
    were already created in migration:

    2a9b1c90c28c
    """

    pass


def downgrade() -> None:
    """
    No operation.

    Schema ownership belongs to the earlier
    delivery migration.
    """

    pass




# """adding delivery partner and assignment

# Revision ID: 6091ef8231c7
# Revises: bde848467272
# Create Date: 2026-10-05 14:13:47.170661

# """

# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa



# # revision identifiers, used by Alembic.
# revision: str = '6091ef8231c7'
# down_revision: Union[str, Sequence[str], None] = 'bde848467272'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
    
    
#     op.drop_constraint(
#         'chk_users_role',
#         'users',
#         type_='check',
#         )
    
#     op.create_check_constraint(
#             'chk_users_role',
#             'users',
#             "role IN ('CUSTOMER', 'DELIVERY_PARTNER', 'ADMIN', 'SUPER_ADMIN')",
#         )
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('delivery_partner_profiles',
#     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.Integer(), nullable=False),
#     sa.Column('vehicle_type', sa.String(length=50), nullable=True),
#     sa.Column('vehicle_number', sa.String(length=50), nullable=True),
#     sa.Column('is_online', sa.Boolean(), nullable=False),
#     sa.Column('is_available', sa.Boolean(), nullable=False),
#     sa.Column('is_approved', sa.Boolean(), nullable=False),
#     sa.Column('current_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
#     sa.Column('current_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
#     sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_delivery_partner_profiles_is_approved'), 'delivery_partner_profiles', ['is_approved'], unique=False)
#     op.create_index(op.f('ix_delivery_partner_profiles_user_id'), 'delivery_partner_profiles', ['user_id'], unique=True)
#     op.create_index(op.f('ix_delivery_partner_profiles_vehicle_number'), 'delivery_partner_profiles', ['vehicle_number'], unique=False)
#     op.create_table('delivery_assignments',
#     sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
#     sa.Column('order_id', sa.Integer(), nullable=False),
#     sa.Column('delivery_partner_id', sa.Integer(), nullable=False),
#     sa.Column('status', sa.String(length=40), nullable=False),
#     sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('out_for_delivery_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
#     sa.Column('rejection_reason', sa.Text(), nullable=True),
#     sa.Column('failure_reason', sa.Text(), nullable=True),
#     sa.Column('delivery_note', sa.Text(), nullable=True),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.ForeignKeyConstraint(['delivery_partner_id'], ['users.id'], ondelete='RESTRICT'),
#     sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_delivery_assignments_delivery_partner_id'), 'delivery_assignments', ['delivery_partner_id'], unique=False)
#     op.create_index(op.f('ix_delivery_assignments_order_id'), 'delivery_assignments', ['order_id'], unique=False)
#     op.create_index('ix_delivery_assignments_order_status', 'delivery_assignments', ['order_id', 'status'], unique=False)
#     op.create_index('ix_delivery_assignments_partner_status', 'delivery_assignments', ['delivery_partner_id', 'status'], unique=False)
#     op.create_index(op.f('ix_delivery_assignments_status'), 'delivery_assignments', ['status'], unique=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_delivery_assignments_status'), table_name='delivery_assignments')
#     op.drop_index('ix_delivery_assignments_partner_status', table_name='delivery_assignments')
#     op.drop_index('ix_delivery_assignments_order_status', table_name='delivery_assignments')
#     op.drop_index(op.f('ix_delivery_assignments_order_id'), table_name='delivery_assignments')
#     op.drop_index(op.f('ix_delivery_assignments_delivery_partner_id'), table_name='delivery_assignments')
#     op.drop_table('delivery_assignments')
#     op.drop_index(op.f('ix_delivery_partner_profiles_vehicle_number'), table_name='delivery_partner_profiles')
#     op.drop_index(op.f('ix_delivery_partner_profiles_user_id'), table_name='delivery_partner_profiles')
#     op.drop_index(op.f('ix_delivery_partner_profiles_is_approved'), table_name='delivery_partner_profiles')
#     op.drop_table('delivery_partner_profiles')
    
    
   
#     # =========================================================
#     # RESTORE OLD USER ROLE CONSTRAINT
#     # =========================================================
#     op.drop_constraint(
#         'chk_users_role',
#         'users',
#         type_='check',
#     )

#     op.create_check_constraint(
#         'chk_users_role',
#         'users',
#         "role IN ('CUSTOMER', 'ADMIN', 'SUPER_ADMIN')",
#     )
#     # ### end Alembic commands ###