"""add delivery otp and cod fields

Revision ID: 72b276f65e52
Revises: 46d6f79124f3
Create Date: 2026-10-05 16:39:06.268419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '72b276f65e52'
down_revision: Union[str, Sequence[str], None] = '46d6f79124f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_assignments', sa.Column('delivery_otp_hash', sa.Text(), nullable=True))
    op.add_column('delivery_assignments', sa.Column('delivery_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_assignments', sa.Column('delivery_otp_attempts', sa.Integer(), nullable=True))
    op.add_column('delivery_assignments', sa.Column('delivery_otp_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('delivery_assignments', sa.Column('cod_collected_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('delivery_assignments', sa.Column('cod_collected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_assignments', 'cod_collected_at')
    op.drop_column('delivery_assignments', 'cod_collected_amount')
    op.drop_column('delivery_assignments', 'delivery_otp_verified_at')
    op.drop_column('delivery_assignments', 'delivery_otp_attempts')
    op.drop_column('delivery_assignments', 'delivery_otp_expires_at')
    op.drop_column('delivery_assignments', 'delivery_otp_hash')
    # ### end Alembic commands ###