"""add delivery otp sent timestamp

Revision ID: cde033dc61c2
Revises: 365ad0daccef
Create Date: 2026-10-05 17:23:11.984176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'cde033dc61c2'
down_revision: Union[str, Sequence[str], None] = '365ad0daccef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_assignments', sa.Column('delivery_otp_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_assignments', 'delivery_otp_sent_at')
    # ### end Alembic commands ###