"""secure phone otp sessions

Revision ID: f4381d7048a9
Revises: 21b4e1fc96bd
Create Date: 2026-09-23 15:49:41.311980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f4381d7048a9'
down_revision: Union[str, Sequence[str], None] = '21b4e1fc96bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_otp_sessions', sa.Column('challenge_id', sa.String(length=64), nullable=False))
    op.add_column('phone_otp_sessions', sa.Column('otp_hash', sa.String(length=64), nullable=False))
    op.add_column('phone_otp_sessions', sa.Column('idempotency_key', sa.String(length=64), nullable=False))
    op.add_column('phone_otp_sessions', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('phone_otp_sessions', 'provider_request_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_phone_otp_sessions_provider_request_id'), table_name='phone_otp_sessions')
    op.create_index(op.f('ix_phone_otp_sessions_provider_request_id'), 'phone_otp_sessions', ['provider_request_id'], unique=False)
    op.create_index(op.f('ix_phone_otp_sessions_challenge_id'), 'phone_otp_sessions', ['challenge_id'], unique=True)
    op.create_unique_constraint(None, 'phone_otp_sessions', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'phone_otp_sessions', type_='unique')
    op.drop_index(op.f('ix_phone_otp_sessions_challenge_id'), table_name='phone_otp_sessions')
    op.drop_index(op.f('ix_phone_otp_sessions_provider_request_id'), table_name='phone_otp_sessions')
    op.create_index(op.f('ix_phone_otp_sessions_provider_request_id'), 'phone_otp_sessions', ['provider_request_id'], unique=True)
    op.alter_column('phone_otp_sessions', 'provider_request_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('phone_otp_sessions', 'attempts')
    op.drop_column('phone_otp_sessions', 'idempotency_key')
    op.drop_column('phone_otp_sessions', 'otp_hash')
    op.drop_column('phone_otp_sessions', 'challenge_id')
    # ### end Alembic commands ###