ORDER_STATUS_PLACED = "PLACED"
ORDER_STATUS_CONFIRMED = "CONFIRMED"
ORDER_STATUS_PROCESSING = "PROCESSING"
ORDER_STATUS_PACKED = "PACKED"
ORDER_STATUS_OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
ORDER_STATUS_DELIVERED = "DELIVERED"
ORDER_STATUS_CANCELLED = "CANCELLED"
ORDER_STATUS_DELIVERY_FAILED = "DELIVERY_FAILED"


ORDER_TRANSITIONS = {

    "PLACED": {
        "CONFIRMED",
        "CANCELLED",
    },

    "CONFIRMED": {
        "PROCESSING",
        "CANCELLED",
    },

    "PROCESSING": {
        "PACKED",
        "CANCELLED",
    },

    "PACKED": {
        "OUT_FOR_DELIVERY",
        "CANCELLED",
    },

    "OUT_FOR_DELIVERY": {
        "DELIVERED",
        "DELIVERY_FAILED",
    },

    "DELIVERED": set(),

    "CANCELLED": set(),

    "DELIVERY_FAILED": set(),
}